### ISSUE TITLE
Installation: 404 error when Add App is pressed

### ISSUE THREAD

**Issue by tillbaks** [maros/Zway-BaseModule#2]
Tried to install this module today (version 1.03). I've updated raspbian and the z-way-server. Then installed this module in different ways but always en up at a 404 page: http://localhost:8083/smarthome/#/error/404
when pressing the "Add App"-button with the error below in the javascript console.

```
---------- Unable to recieve HTTP data ---------- 404
(anonymous function) @ build.js:7574
logError @ build.js:9550
showConnectionError @ build.js:9524
$scope.loadError @ build.js:11849
(anonymous function) @ build.js:11852
d @ build.js:7517
instantiate @ build.js:7517
(anonymous function) @ build.js:7549
(anonymous function) @ build.js:7536
r @ build.js:7489
J @ build.js:7535
g @ build.js:7529
(anonymous function) @ build.js:7528
link @ build.js:7709
J @ build.js:7536
g @ build.js:7529
(anonymous function) @ build.js:7528
(anonymous function) @ build.js:7530
w @ build.js:7534
v @ build.js:7708
h.$broadcast @ build.js:7597
(anonymous function) @ build.js:7713
J @ build.js:7583
J @ build.js:7583
(anonymous function) @ build.js:7584
h.$eval @ build.js:7595
h.$digest @ build.js:7592
h.$apply @ build.js:7595
m @ build.js:7554
w @ build.js:7559
B.onreadystatechange @ build.js:7561
```

Z-way-server:
Firmware version    v2.2.0
UI version  1.0.3

Nothing is logged in /var/log/z-way-server.log

**Comment by maros** [comment]
Please increase the loglevel and post the respective log entries from /var/log/z-way-server.log. I'm afraid that the output from the JS console won't help here.

**Comment by tillbaks** [comment]
I do have debug logging enabled but there are no logs created when I press the button.

```
root@raspberrypi:/opt/z-way-server# cat config.xml 
<config>
    <automation-dir>automation</automation-dir>
    <log-file>/var/log/z-way-server.log</log-file>
    <log-level>0</log-level>
    <http-log-file>/var/log/z-way-server-http.log</http-log-file>
    <http-log-level>0</http-log-level>
    <debug-port></debug-port>
</config>
```

Theres a few errors like this when I open the webpage. Probably unrelated?

```
[2016-02-10 22:18:38.949] [E] [8083] Callback execution error: TypeError: Cannot read property 'call' of undefined
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:40)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)

```

**Comment by tillbaks** [comment]
Well.. I tried moving my very old z-way-server installation and try a fresh installation. It works now. So the problem is somewhere in the z-way-server I guess.
